[package]
name = "rraft"
version = "0.1.0"
edition = "2021"
keywords = ["raft"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["proto", "harness", "datadriven"]

[dependencies]
